#!/bin/bash

## SERVICE MONITOR
## HTTP
HTTP_URLS=(http://www.nsiautostore.com/software/ricoh/ricohoverview 74.208.44.64/software/ricoh/ricohoverview)

while [ true ]; do
	for i in ${HTTP_URLS[@]}; do
		RES=(`curl\
		 --connect-timeout 30\
		 -m 40\
		 --silent\
		 --trace-time\
		 -w "%{http_connect} %{http_code} %{time_namelookup} %{time_connect} %{time_pretransfer} %{time_redirect} %{time_starttransfer} %{time_total}"\
		 -o ./out\
		 "$i"` $i)
		echo ${RES[*]}
	done
done

